module.exports = {
  en: {
    label: 'GC Design System',
    home: 'Home',
    contact: 'Contact',
    contactus: 'Contact us',
    colourtokens: 'Colour tokens',
    components: 'Components',
    componentsoverview: 'Components overview',
    cssshortcuts: 'CSS shortcuts',
    cssshortcutsoverview: 'CSS shortcuts overview',
    spacingtokens: 'Spacing tokens',
    typographytokens: 'Typography tokens',
    designtokens: 'Design tokens',
    getinvolved: 'Get involved',
    starttouse: 'Start to use',
    finddemo: 'Find a demo',
    pagetemplates: 'Page templates',
    pagetemplatesoverview: 'Page templates overview',
    stylesoverview: 'Styles overview',
  },
  fr: {
    label: 'Système de design GC',
    home: 'Accueil',
    contact: 'Contact',
    contactus: 'Contactez-nous',
    colourtokens: 'Unités de style de couleur',
    components: 'Composants',
    componentsoverview: 'Aperçu des composants',
    cssshortcuts: 'Raccourcis CSS',
    cssshortcutsoverview: 'Aperçu des raccourcis CSS',
    spacingtokens: "Unités de style d'espacement",
    typographytokens: 'Unités de style typographie',
    designtokens: 'Unités de style',
    getinvolved: 'Impliquez-vous',
    starttouse: 'Démarrer',
    finddemo: 'Trouvez une démo',
    pagetemplates: 'Modèles de page',
    pagetemplatesoverview: 'Aperçu des modèles de page',
    stylesoverview: 'Aperçu des styles',
  },
};
