module.exports = {
  en: {
    grayscale: 'Gray',
    blue: 'Blue',
    red: 'Red',
    green: 'Green',
    yellow: 'Yellow',
    purple: 'Purple',
    black: 'Black',
    white: 'White',
    blueVivid: 'Blue vivid',
    blueMuted: 'Blue muted',
  },
  fr: {
    grayscale: 'Gris',
    blue: 'Bleu',
    red: 'Rouge',
    green: 'Vert',
    yellow: 'Jaune',
    purple: 'Violet',
    black: 'Noir',
    white: 'Blanc',
    blueVivid: 'Bleu vif',
    blueMuted: 'Bleu doux',
  },
};
