name: A11y test documentation site

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'reports/**'
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - package.json
      - package-lock.json
      - .eleventy.js
      - src/**
      - utils/**
      - .github/workflows/a11y-tests.yaml
      - cypress/**
      - scripts/templates.js

jobs:
  a11y-test:
    name: ${{ matrix.test.name }}
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        test:
          - name: English site
            spec: cypress/e2e/a11y-en.cy.js
            url: 'http://localhost:8080/en'
          - name: French site
            spec: cypress/e2e/a11y-fr.cy.js
            url: 'http://localhost:8080/fr'

    steps:
      - name: Git Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: '18'

      - name: Cypress run
        uses: cypress-io/github-action@2ad32e649e4db26c07674ebae31a297601dbcbaf # v6.10.8
        with:
          build: npm run build:eleventy
          start: npm run watch:eleventy
          wait-on: ${{ matrix.test.url }}
          # wait for 2 minutes for the server to respond
          wait-on-timeout: 240
          spec: ${{ matrix.test.spec }}
