name: API Tests

on:
  push:
    paths:
      - 'api/src/**'
      - '.github/workflows/api-tests.yaml'
  pull_request:
    paths:
      - 'api/src/**'
      - '.github/workflows/api-tests.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api/src
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test 